apiVersion: v1
kind: Pod
metadata:
  name: kplabs-multi-container
spec:
  containers:
  - image: nginx
    name: first-container
  - image: mykplabs/kubernetes:nginx
    name: second-container
  - image: busybox
    name: third-container
    command:
    - sleep
    - '3600'
