apiVersion: v1
kind: Pod
metadata:
  name: kplabs-troubleshoot
spec:
  containers:
  - image: busybox
    name: troubleshoot-container
    command:
    - /bin/sh
    - -c
    args: ["-c", "while true; do echo hello; sleep 10;done"]
