heat_template_version: 2015-04-30

parameters:
  ipam1_name:
    type: string
    description: Name of the IPAM
  subnet1_uuid:
    type: string
    description: UUID of the IPAM subnet
  ipam2_name:
    type: string
    description: Name of the IPAM
  subnet2_uuid:
    type: string
    description: UUID of the IPAM subnet
  vn1_name:
    type: string
    description: Name of the network
  subnet1_prefix:
    type: string
    description: prefix for subnet1
  subnet2_prefix:
    type: string
    description: prefix for subnet2
  subnet_prefix_len:
    type: string
    description: prefix length for subnets
  addr_from_start_true:
    type: string
    description: Subnet address start flag


resources:
  ipam1:
    type: OS::ContrailV2::NetworkIpam
    properties:
      name: { get_param: ipam1_name }
  ipam2:
    type: OS::ContrailV2::NetworkIpam
    properties:
      name: { get_param: ipam2_name }

  vn1:
    type: OS::ContrailV2::VirtualNetwork
    properties:
      name: { get_param: vn1_name }
      network_ipam_refs: [{ get_resource: ipam1 }, { get_resource: ipam2 }]
      network_ipam_refs_data:
        [{
          network_ipam_refs_data_ipam_subnets:
            [{
              network_ipam_refs_data_ipam_subnets_subnet:
                {
                  network_ipam_refs_data_ipam_subnets_subnet_ip_prefix: { get_param: subnet1_prefix },
                  network_ipam_refs_data_ipam_subnets_subnet_ip_prefix_len: { get_param: subnet_prefix_len },
                },
          network_ipam_refs_data_ipam_subnets_addr_from_start: { get_param: addr_from_start_true },
          network_ipam_refs_data_ipam_subnets_subnet_uuid: { get_param: subnet1_uuid },
            }],
            },
           {
           network_ipam_refs_data_ipam_subnets:
            [{
             network_ipam_refs_data_ipam_subnets_subnet:
                {
                  network_ipam_refs_data_ipam_subnets_subnet_ip_prefix: { get_param: subnet2_prefix },
                  network_ipam_refs_data_ipam_subnets_subnet_ip_prefix_len: { get_param: subnet_prefix_len },
                },
          network_ipam_refs_data_ipam_subnets_addr_from_start: { get_param: addr_from_start_true },
          network_ipam_refs_data_ipam_subnets_subnet_uuid: { get_param: subnet2_uuid },
            }]
         }]

  vmi1:
    type: OS::ContrailV2::VirtualMachineInterface
    properties:
      virtual_network_refs: [{ list_join: [':', { get_attr: [ vn1, fq_name ] } ] }]
  iip1:
    type: OS::ContrailV2::InstanceIp
    properties:
      virtual_machine_interface_refs: [{ get_resource: vmi1 }]
      virtual_network_refs: [{ list_join: [':', { get_attr: [ vn1, fq_name ] } ] }]
      network_ipam_refs: [{ list_join: [':', { get_attr: [ ipam2, fq_name ] } ] }]
      subnet_uuid: { get_param: subnet2_uuid }

outputs:
  iip1_ip:
    description: Instance IP
    value: { get_attr: [ iip1, instance_ip_address ] }
