apiVersion: v1
kind: Pod
metadata:
  name: fabricpod
  namespace: gani-ns-isolated
  annotations:
    opencontrail.org/network: '{"domain":"default-domain", "project":"k8s-gani-ns-isolated", "name": "k8s-vn-gani-ns-isolated-pod-network" }'
spec:
  containers:
      - image: ubuntu-upstart
        name: ubuntu
