apiVersion: v1
kind: Pod
metadata:
  name: nodeselector-pod2
  namespace: gani-ns-isolated
  annotations:
    opencontrail.org/network: '{"domain":"default-domain", "project":"k8s-gani-ns-isolated", "name": "k8s-vn-gani-ns-isolated-pod-network" }'
spec:
  containers:
      - image: ubuntu-upstart
        name: ubuntu-with-nodeselector
  nodeSelector:
    role: worker1   ### Used to select the worker node to launch the Pod
